import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { Analytics } from "@vercel/analytics/next";

import FooterBlur from "@/components/Footer/FooterBlur";
import NavBar from "@/components/Navbar/NavBar";
import { ThemeProvider } from "@/hooks/ThemeProvider";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000"
  ),
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    images: [
      {
        url: "/og_image.png",
        width: 1200,
        height: 630,
        alt: "Open Graph Image",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    images: ["/og_image.png"],
  },
};

// Script to prevent flash of incorrect theme
const themeInitScript = `
  (function() {
    try {
      const savedTheme = localStorage.getItem('theme');
      const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
      if (savedTheme === 'light') {
        document.documentElement.classList.remove('dark');
      } else {
        document.documentElement.classList.add('dark');
      }
    } catch (e) {}
  })();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
        <link rel="preload" href="/Logo.webp" as="image" type="image/webp" />
        <link rel="preload" href="/x.webp" as="image" type="image/webp" />
        <link
          rel="preload"
          href="/linkedin.webp"
          as="image"
          type="image/webp"
        />
        <link
          rel="preload"
          href="/instagram.webp"
          as="image"
          type="image/webp"
        />
        <link
          rel="preload"
          href="/pinterest.webp"
          as="image"
          type="image/webp"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          {/* Decorative diagonal stripe borders flush with content */}
          <div
            className="pointer-events-none fixed inset-y-0 z-[999] hidden w-[60px] overflow-hidden sm:block"
            style={{ left: "calc(50% - 360px - 65px)" }}
          >
            <div
              className="absolute inset-0 h-full w-[60px] border border-[#000]/70 opacity-[0.06] dark:border-[#eee] dark:opacity-[0.04]"
              style={{
                backgroundImage:
                  "repeating-linear-gradient(-45deg, transparent, transparent 2px, currentcolor 2px, currentcolor 3px, transparent 3px, transparent 6px)",
              }}
            />
          </div>
          <div
            className="pointer-events-none fixed inset-y-0 z-[999] hidden w-[60px] overflow-hidden sm:block"
            style={{ left: "calc(50% + 365px)" }}
          >
            <div
              className="absolute inset-0 h-full w-[60px] border border-[#000]/70 opacity-[0.06] dark:border-[#eee] dark:opacity-[0.04]"
              style={{
                backgroundImage:
                  "repeating-linear-gradient(-45deg, transparent, transparent 2px, currentcolor 2px, currentcolor 3px, transparent 3px, transparent 6px)",
              }}
            />
          </div>
          <NavBar />
          {children}
          <FooterBlur />
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
