import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";

import FooterBlur from "@/components/Footer/FooterBlur";
import NavBar from "@/components/Navbar/NavBar";
import { ThemeProvider } from "@/hooks/ThemeProvider";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Script to prevent flash of incorrect theme
const themeInitScript = `
  (function() {
    try {
      const savedTheme = localStorage.getItem('theme');
      const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
      if (savedTheme === 'dark' || (!savedTheme && prefersDark)) {
        document.documentElement.classList.add('dark');
      } else {
        document.documentElement.classList.remove('dark');
      }
    } catch (e) {}
  })();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          {/* Decorative diagonal stripe borders flush with content */}
          <div
            className="pointer-events-none fixed inset-y-0 z-[999] hidden w-[60px] overflow-hidden sm:block"
            style={{ left: "calc(50% - 360px - 60px)" }}
          >
            <div
              className="absolute inset-0 h-full w-[60px] border border-[#000]/70 opacity-[0.06] dark:border-[#eee] dark:opacity-[0.04]"
              style={{
                backgroundImage:
                  "repeating-linear-gradient(-45deg, transparent, transparent 2px, currentcolor 2px, currentcolor 3px, transparent 3px, transparent 6px)",
              }}
            />
          </div>
          <div
            className="pointer-events-none fixed inset-y-0 z-[999] hidden w-[60px] overflow-hidden sm:block"
            style={{ left: "calc(50% + 362px)" }}
          >
            <div
              className="absolute inset-0 h-full w-[60px] border border-[#000]/70 opacity-[0.06] dark:border-[#eee] dark:opacity-[0.04]"
              style={{
                backgroundImage:
                  "repeating-linear-gradient(-45deg, transparent, transparent 2px, currentcolor 2px, currentcolor 3px, transparent 3px, transparent 6px)",
              }}
            />
          </div>
          <NavBar />
          {children}
          <FooterBlur />
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
